changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Fix Problems
      labels:
        - fix
    - title: Other Changes
      labels:
        - "*"