---
name: aqua test
on:
  push:
    paths:
      - .github/workflows/aqua-test.yaml

env:
  AQUA_CONFIG: .github/aqua/ci.yaml

permissions: {}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.8.0
        # env:
        #   AQUA_CONFIG: .github/aqua/ci.yaml
      - run: |
          echo $AQUA_CONFIG
          ghcp -v
          ghalint -v