name: check-labels
on:
  push:
    paths:
      - .github/workflows/check-labels-action.yaml
  workflow_call:
    inputs:
      REVIEWERS:
        required: false
        type: string
      LABELS:
        required: false
        type: string

permissions: {}

jobs:
  check-labels:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: |
          labels="Release, test"
          # カンマで分割して空白を除去して配列に格納
          IFS=',' read -r -a labels_array <<< "$(echo "$labels" | tr -d '[:space:]')"

          # 配列の要素を改行して表示
          for label_name in "${labels_array[@]}"; do
              echo "$label_name"
              if ! $(gh label list --json name | jq ". | any(.name == \"${label_name}\")"); then
                  echo "${label}は存在しないよ！"
              fi
          done
    env:
      GITHUB_TOKEN: ${{github.token}}
