name: check-labels
on:
  push:
    paths:
      - .github/workflows/check-labels-action.yaml
  workflow_call:
    inputs:
      REVIEWERS:
        required: false
        type: string
      LABELS:
        default: "Release test"
        required: false
        type: string

permissions: {}

env:
  label_name: ${{inputs.LABELS || 'Release test'}}

jobs:
  check-labels:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: |
          labels=${{env.label_name}}
          # カンマで分割して空白を除去して配列に格納
          IFS=',' read -r -a labels_array <<< "$(echo "$labels" | tr -d '[:space:]')"

          # 配列の要素を改行して表示
          for label in "${labels_array[@]}"; do
              echo "$label"
              # if ! $(gh label list --json name | jq ". | any(.name == \"${label}\")"); then
              #     echo "${label}は存在しないよ！"
              # fi
          done
    env:
      GITHUB_TOKEN: ${{github.token}}
