name: check-labels
on:
  workflow_call:
    inputs:
      REVIEWERS:
        required: false
        type: string
      LABELS:
        required: false
        type: string

permissions: {}

jobs:
  check-labels:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: |
          labels=${{inputs.LABELS}}
          # カンマで分割して空白を除去して配列に格納
          IFS=',' read -r -a labels <<< "$(echo "$labels" | tr -d '[:space:]')"

          # 配列の要素を改行して表示
          for label in "${labels[@]}"; do
              echo "$label"
              if ! $(gh label list --json name | jq ". | any(.name == \"${label}\")"); then
                  echo "${label}は存在しないよ！"
              fi
          done
    env:
      GITHUB_TOKEN: ${{github.token}}
