---
name: default test
on:
  # push:
  #   paths:
  #     - .github/workflows/default-test.yaml
  workflow_call:
    inputs:
      input1:
        required: false
        type: string
        default: |
          {
            "categories": [
              {
                  "title": "## Features",
                  "labels": [
                    "feature",
                    "enhancement"
                  ]
              },
              {
                  "title": "## Fixes",
                  "labels": ["fix"]
              },
              {
                  "title": "## Tests",
                  "labels": ["test"]
              }
              {
                  "title": "## Others",
                  "labels": ["other"]
              },
              {
                  "title": "## Dependencies",
                  "labels": ["dependencies"]
              }
            ],
            "template": "#{{CHANGELOG}}"
          }
permissions: {}
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "inputs.input1 is ${{toJson(inputs.input1)}}"
      - name: Build Changelog
        id: github_release
        if: success()
        uses: mikepenz/release-changelog-builder-action@v4.0.0-b02
        with:
          fromTag: 'v0.0.0'
          toTag: ${{ github.ref }}
          configurationJson: |
            ${{toJson(inputs.input1)}}
      - run: echo "${{steps.github_release.outputs.changelog}}"