---
name: reuseable default actions test
on: workflow_dispatch
permissions: {}
jobs:
  default-wc:
    uses: ./.github/workflows/default-test.yaml
    with:
      input1: |
        {
          "template": "#{{CHANGELOG}}\n\nUncategorized\n#{{UNCATEGORIZED}}",
          "categories": [
            {
                "title": "## 💬 Other",
                "labels": ["other"]
            },
            {
                "title": "## 📦 Dependencies",
                "labels": ["dependencies"]
            }
          ]
        }
