---
name: ghcp test
on: workflow_dispatch
permissions: {}
jobs:
  build-changelog:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      changelog: ${{steps.github_release.outputs.changelog}}
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4.0.0-b02
        with:
          fromTag: v0.0.0
          toTag: ${{ github.ref }}
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_TEMPLATE: |-
            **Epics**
            #{{CHANGELOG}}
            
            <details>
            <summary>Uncategorized</summary>
            
            #{{UNCATEGORIZED}}
            </details>
      - run: echo "${{steps.github_release.outputs.changelog}}"
  # run-ghcp:
  #   needs: build-changelog
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #   steps:
  #     - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
  #     - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
  #       with:
  #         aqua_version: v2.8.0
  #     - name: Generate token
  #       id: generate_token
  #       uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
  #       with:
  #         app_id: ${{secrets.gh_app_id}}
  #         private_key: ${{secrets.gh_app_private_key}}
  #     - run: |
  #         ghcp -v
  #         SAME_PR_COUNT=$(gh pr list -B $GITHUB_REF_NAME -H release/v0.0.0 --json 'id' --jq '.[] | length')
  #         if [[ -z "$SAME_PR_COUNT" ]]; then
  #           ghcp empty-commit -r $GITHUB_REPOSITORY -b release/v0.0.0 -m 'chore: empty commit to open follow up pull request'
  #           gh pr create -B $GITHUB_REF_NAME -H release/v0.0.0 --title v0.0.0 --body "$CHANGELOG" --reviewer murn0
  #         else
  #           SAME_PR_NUMBER=$(gh pr list -B $GITHUB_REF_NAME -H release/v0.0.0 --json 'number' --jq '.[].number')
  #           gh pr edit $SAME_PR_NUMBER --title 'v0.0.0 [edit]' --body "$CHANGELOG"
  #         fi
  #       env:
  #         GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
  #         CHANGELOG: ${{needs.build-changelog.outputs.changelog}}