---
name: test
on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions: {}
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
  create-release-draft:
    runs-on: ubuntu-latest
    permissions: {}
    if: |
      github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
      - name: Generate pull request
        run: |
          set -eu
          
          gh release create "${{github.event.pull_request.title}}" --draft --notes "${{github.event.pull_request.body}}" --target ${{ github.sha }} --title "Release: ${{github.event.pull_request.title}}"
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}