---
name: test
on:
  # push:
  #   paths:
  #     - .github/workflows/test.yaml
  pull_request:
    branches:
      - main
    types:
      - closed
permissions: {}
jobs:
  create-release-draft:
    uses: murn0/generate-release-workflow/.github/workflows/release.yaml@main
    permissions: {}
    if: |
      github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    with:
      draft: true
    secrets:
      gh_app_id: ${{secrets.GH_APP_ID}}
      gh_app_private_key: ${{secrets.GH_APP_PRIVATE_KEY}}