---
name: test
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
permissions: {}
jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    permissions: {}
    if: |
      github.triggering_actor == 'murn0' && startsWith(github.event.label.name, 'release')
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Bump version
        run: |
          gh release list --limit 10
        env:
          GITHUB_TOKEN: ${{github.token}}