---
name: test
on:
  push:
    paths:
      - .github/workflows/test.yaml
  pull_request:
    branches:
      - main
    types:
      - closed
permissions: {}
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # cat $GITHUB_EVENT_PATH
          title=${REF#refs/heads/}

          echo "title is $title"
        env:
          REF: ${{github.ref}}
  create-release-draft:
    runs-on: ubuntu-latest
    permissions: {}
    if: |
      github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
      - name: Generate pull request
        run: |
          set -eu
          
          gh release create "${HEAD_REF#release/}" --draft --notes "${BODY//\\/\\\\}" --target ${{github.sha}} --title "Release: ${HEAD_REF#release/}"
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
          HEAD_REF: ${{github.event.pull_request.head.ref}}
          BODY: ${{github.event.pull_request.body}}