---
name: test
on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions: {}
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
  create-release-draft:
    runs-on: ubuntu-latest
    permissions: {}
    if: |
      github.event.pull_request.merged == true
    steps:
      - run: |
          echo "SHA is $GITHUB_SHA"
          echo "REF is $GITHUB_REF"