---
name: test
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
permissions: {}
jobs:
  create-release-draft:
    runs-on: ubuntu-latest
    permissions: {}
    if: |
      startsWith(github.event.label.name, 'Release')
    steps:
      - run: |
          echo "SHA is $GITHUB_SHA"
          echo "REF is $GITHUB_REF"